[server]
http_port = 3000
domain = grafana.quiz-app.internal

[security]
admin_user = admin
; admin_password is set via GF_SECURITY_ADMIN_PASSWORD env var

[auth.anonymous]
enabled = false

[dashboards]
default_home_dashboard_path = /etc/grafana/dashboards/quiz-app-dashboard.json

[alerting]
enabled = true

[unified_alerting]
enabled = false

[smtp]
enabled = true
host = smtp.gmail.com:587
from_address = grafana@quiz-app.internal
