apiVersion: v1
kind: Service
metadata:
  name: quiz-app
  namespace: quiz-app
spec:
  selector:
    app: quiz-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1112
      nodePort: 30112
